apiVersion: v1
kind: ReplicationController
metadata:
  name: techgigrc1
spec:
  replicas: 3
  selector:
    env: stg
  template:
    metadata:
      name: techgigrc1
      labels:
        env: stg
    spec:
      containers:
      - name: techgig-stg
        image: sunilkumar1984/linux_based:techgig
        ports:
        - containerPort: 80

