kind: PersistentVolume
apiVersion: v1
metadata:
  name: tg-volume
  labels:
    type: stg
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/techgig"

